buildpacks/spec

platform.md

[https://github.com/buildpack/spec/issues/16]

Require build image to provide PACK_{USER,GROUP}_ID

---

buildpack.md

As requested by @hone for preserving defaults chosen on the first build.

Add persistent store for default initialized values that survives a cache clear

---

platform.md

From RFC: https://github.com/buildpack/rfcs/pull/13

Stage-specific Mixins

---

buildpack.md

Signed-off-by: Emily Casey <ecasey@pivotal.io>

typographical fixes

---

README.md

Signed-off-by: Stephen Levine <stephen.levine@gmail.com>

Add API versions to spec

---

extensions/bindings.md

* the source of these binding will be platform specific
Signed-off-by: Emily Casey <ecasey@pivotal.io>

The platform should be responsible for injecting the bindings

---

extensions/buildpack-registry.md

Based on [RFC-0022](https://github.com/buildpacks/rfcs/blob/master/text/0022-client-side-buildpack-registry.md) and [RFC-0032](https://github.com/buildpacks/rfcs/blob/master/text/0032-update-json-cnb-registry.md).

Added a buildpack registry extension

---

extensions/buildpack-registry.md

Incorporates the following RFCs:
* [RFC-0022](https://github.com/buildpacks/rfcs/blob/main/text/0022-client-side-buildpack-registry.md)
* [RFC-0032](https://github.com/buildpacks/rfcs/blob/main/text/0032-update-json-cnb-registry.md)
* [RFC-0044](https://github.com/buildpacks/rfcs/blob/main/text/0044-pack-publish-buildpack.md)

Update Buildpack Registry Extension

---

platform.md

Resolves https://github.com/buildpacks/spec/issues/47

Specify build reproducibily

---

platform.md

Context in [this slack thread](https://buildpacks.slack.com/archives/CSFE49VGR/p1594912690185400)
Signed-off-by: David Freilich <dfreilich@vmware.com>

Add buildpacks input to creator spec

---

platform.md

Specify report.toml

---

platform.md

Multicall launcher

---

platform.md

Homepage in build metadata label

---

buildpack.md

* uses "Layer Content Metadata" instead of `<layers>/<layer>.toml` in situations where the layer metadata is not store in a `<layer>.toml` file and vice versa
* removes conflicting requirements between layer types (so readers do not have to determine which is more "strict")
* describes the behavior of layer where launch, build, and cache are all false
Resolves #103
cc @ryanmoran
NOTE: There is no functional change to the API here. This change is purely for clarity/readability.

Adds "Cached Layers" to Layer Types

---

platform.md

Adds build BOM to report.toml

---

buildpack.md

It took me some time to understand that the `lifecycle` is a program and not a concept.

buildpack.md Reword intro in simple English

---

platform.md

Based on [RFC 114](https://github.com/buildpacks/rfcs/pull/114)
Signed-off-by: Micah Young <ymicah@vmware.com>

Changes platform spec to ensure image config Env PATH is set

---

platform.md

Signed-off-by: Micah Young <ymicah@vmware.com>

Fixes typo in platform spec

---

platform.md

Add Image Manifest Size to report.toml

---

buildpack.md

Clarify launcher env

---

buildpack.md

Finalize buildpack API 0.6
[Draft release notes](https://github.com/buildpacks/spec/releases/tag/untagged-7b40f3b24e9707ffc218)

Buildpack API 0.6

---

buildpack.md
platform.md

Relax mixin contract platform changes. This was split out at @hone's request. But is a subset of #210

0061 Relax mixin contract platform

---

extensions/project-descriptor.md

This implements #219 and buildpacks/rfcs#140.
I wasn't sure if we should split these into two separate files or not. For this first pass I stuck to putting everything into one.

Project Descriptor Reverse Domain RFC

---

extensions/project-descriptor.md

Add spec for RFC-0048 Inline Buildpacks

---

extensions/project-descriptor.md

Add inline buildpack example to project-desc spec

---

README.md
platform.md

Updates platform API version to 0.7 in README and platform spec.

Updates platform API version in spec and README

---

README.md
distribution.md

Updates distribution API version to 0.3 in README and platform spec.

Updates distribution API version in spec and README

---

platform.md

fix typo referenceing -> referencing

---

README.md
platform.md

Note to maintainers: please see draft release note on the [releases page](https://github.com/buildpacks/spec/releases)
Milestone: https://github.com/buildpacks/spec/milestone/14?closed=1

Finalize Platform API 0.7

---

extensions/project-descriptor.md

Signed-off-by: Sambhav Kothari <skothari44@bloomberg.net>

Add schema version to the example

---

CONTRIBUTING.md
RELEASE.md

Documents the lifecycle of a spec release.
Resolves #239

Adds RELEASE.md

---

README.md

Note to maintainers: please see draft release note on the releases page
Milestone: https://github.com/buildpacks/spec/milestone/18

Finalize Platform API 0.8

---

README.md
buildpack.md

Note to maintainers: please see draft release note on the releases page
Milestone: https://github.com/buildpacks/spec/milestone/13

Finalize Buildpack API 0.7

---

distribution.md

This PR consists the artifact format and the delivery mechanism for the Runtime Base Image.

Distribution Specs (v3) - Runtime Base Image Distribution Spec

---

platform.md

Process specific working directory

---

platform.md

Reverts buildpacks/spec#308
This should have been merged into `platform/0.10`, not `main`!

Revert "Platform api changes to support phase 1 of Dockerfiles implementation"

---

platform.md

Issue #322
Signed-off-by: Jesse Brown <jabrown85@gmail.com>

Update launcher spec to support default process args

---

buildpack.md
image_extension.md

Buildpack api changes to support phase 2 of Dockerfiles implementation

---

platform.md

Handles https://github.com/buildpacks/rfcs/pull/262
Signed-off-by: Jesse Brown <jabrown85@gmail.com>

Add `<previous-image>` to rebaser

---

platform.md

Branching off of stack removal for the time being

Platform API changes for run image extension (Dockerfiles phase 3)

---

platform.md

Fixes https://github.com/buildpacks/spec/issues/364

Add insecure registries flags and env var

---

platform.md

Small little change, but the rendering is weird after this point because it's missing the closing backtick.

Close code fence
