buildpacks/spec

- platform.md
- Remove URIs (where never discussed thoroughly, and probably don't make sense because they would need to be repeated for no reason.)
- Add label metadata to groups (to enable the platform to explicitly choose a group with re-specifying all the buildpacks in it).
> [platform] Add labels to order.toml, remove URIs

- buildpack.md
> Enhance build plan and expose env vars during detection

- buildpack.md
As described in #28, this change moves the `<layers[EIC]>` argument to the `$1` position for both `bin/build` and `bin/develop`.
> Move layer argument to $1 for bin/build and bin/develop

- buildpack.md
- platform.md
Specifies #23.
Note: this further simplifies the initial proposal in #23 such that layers have three properties:
1. `cache`
2. `build`
3. `launch`
Such that cached launch layers are fully cache-coherent and always restored.
> Merge cache and launch directories

- buildpack.md
This would increase buildpack portability between platforms that provide fully-coherent caching and platforms that do not.
I'm not convinced this is a good idea (as it will hurt performance in some cases), but I'm opening this PR for discussion.
> Simplify caching by reducing launch+cache outcomes

- buildpack.md
This will support https://github.com/buildpack/lifecycle/pull/96 and ultimately a better way for pack to name directories and files.
> Added constraints for version in buildpack.toml

- buildpack.md
Lifecycle PR: https://github.com/buildpack/lifecycle/pull/147
> More complete environment variable handling

- buildpack.md
This allows buildpacks and app developers to bypass Bash, thus enabling scratch containers.
Implementation: https://github.com/buildpack/lifecycle/pull/148
> Add support for scratch containers

- README.md
- buildpack.md
- distribution.md
- platform.md
This PR makes the spec compatible with https://github.com/buildpack/rfcs/pull/11.
Implementation PR: https://github.com/buildpack/lifecycle/pull/149
> Distribution Specification

- buildpack.md
- distribution.md
Implements: https://github.com/buildpack/rfcs/pull/14
> Load user-provided variables by default

- buildpack.md
- distribution.md
* resolution of order buildpacks is part of the lifecycle/buildpack contract
* removes build-image and run-image from buildpack.toml (buildpack.toml shouldn't include packaging conerns)
Signed-off-by: Emily Casey <ecasey@pivotal.io>
> Move order resolution and buildpack.toml data format to buildpack spec

- buildpack.md
Signed-off-by: Micah Young <myoung@pivotal.io>
Signed-off-by: Emily Casey <ecasey@pivotal.io>
> Adds api to buildpack.toml schema

- buildpack.md
I propose removing this temporarily. We should bring it back when the platform API supports it and after we have validated the interface with a working example.
As it stands, it confuses readers of the spec who assume it is a feature on par with `/bin/detect` and `/bin/build`.
> remove /bin/develop from buildpack API

- extensions/project-descriptor.md
Derived from [RFC 32](https://github.com/buildpacks/rfcs/pull/32).
> Added a project.toml extension

- extensions/bindings.md
Previously, the specification required a `tags` file that contained a set of arbitrary data.  This hasn't been used for anything particularly useful to date, and it has been pointed out that allowing arbitrary files in metadata can achieve the same ends.
Because of these observations, this change removes tags from the specification.
> Remove Tags

- buildpack.md
This change is the specification change required to support [RFC #0034](https://github.com/buildpacks/rfcs/blob/master/text/0034-image-labels.md).
> Image Labels

- buildpack.md
This change implements the updates from buildpacks/rfcs#82.
> Remove version

- buildpack.md
The description of the interpretation of launcher arguments belongs in the platform API because it the contract being described is between the platform and the lifecycle. In the buildpack API spec we should exclusively specify how buildpack provided outputs interact with the launch process.
> Removes platform/launcher contract from buildpack API spec

- buildpack.md
Lifecycle must read buildpack API from buildpack.toml and either respect it or fail
Resolves #93 
Related RFC: https://github.com/buildpacks/rfcs/blob/main/text/0041-api-version-compat.md
> Buildpack API Modes

- buildpack.md
This is a first pass at adding deprecations to the Buildpack API. Maybe some of this should be moved to release notes.
> Version Deprecation

- platform.md
> Removes version key from bom in io.buildpacks.build.metadata.label

- platform.md
* Defines specific error codes for API incompatibilities
* Don't use the same codes for detect and build errors, to avoid ambiguity when using creator
* Error code ranges indicate phase - useful for consumers of creator
I am happy to take the phase specific ranges out if it is controversial but I think the first two bullet points above are important changes to get into platform 0.4.
> More exit code definition

- buildpack.md
Remove buildpack API changes from platform/0.4 (windows buidpacks)
> Remove buidpack API changes from platform/0.4

- buildpack.md
Move windows buildpacks changes from `platform/0.4` to `buildpack/0.4` 
Resolves #119
> Windows buildpacks

- platform.md
While implementing https://github.com/buildpacks/lifecycle/issues/333, it started to feel obvious that `rebaser` should also write a `report.toml` file. Rebase also generates a new app image and consumers need to know the digest of the new image.
Future Considerations:
When we eventually add new fields to the `report.toml` schema, `rebaser` should only populate fields that are relevant to rebase.
> rebase report

- platform.md
Now that we have buidpack API dependent launch logic, the launcher needs the api of each buildpack to exist in metadata.toml so it can do the right thing
* See #116 for an example (arg parsing for direct=false processes)
Other phases may have buidpack API dependent logic as well. Adding the `api` to group.toml will provide this the api of each buildpack everywhere it is needed.
> Buildpack API in group and metadata

- platform.md
This has been a frequent request of the lifecycle. Default file paths relative to the working dir are confusing because we provide no guidance on what the working directory should be when the platform executes the lifecycle. Making defaults relative to layers is better because, when phases are executed in separate containers these files should exist on a volume so they may be passed between phases. Right now if a user changes the layers dir they must also change the path of group.toml, plan.toml, etc so that they files are passed between phases. This is annoying. If the defaults are relative to <layers>, changing the layers dir "just works" without requiring a variety of other flags.
> Change defaults that depending on the working dir

- buildpack.md
> Decouple BOM and build plan

- buildpack.md
* makes override the default behavior for env files w/o a suffix
* ~reorders modification types so that the default behavior is easy to find (at the top)~
* reorders modification types alphabetically and moves suffix -> type mapping to a table at the top of the section.
> Override env vars

- platform.md
RFC - https://github.com/buildpacks/rfcs/pull/78
> Updates platform spec for stack metadata RFC

- buildpack.md
Character restrictions in process type strings allow us to make process type symlinks on both linux and windows filesystems
Character restrictions should have been included in [RFC 0045](https://github.com/buildpacks/rfcs/blob/main/text/0045-launcher-arguments.md). This was [discussed](https://github.com/buildpacks/rfcs/pull/84#discussion_r442380422) during the RFC approval process, and was mistakenly omitted from the final RFC & spec.
> Adds character restrictions for process types.

- distribution.md
Updates layer expectations for Windows buildpackages
Signed-off-by: Andrew Meyer <meyeran@vmware.com>
----
This change accommodates Windows buildpackages, which currently require a base image in order to be pulled into a local docker daemon. ~~This may change in the future, and the clarification to the spec will allow for this flexibility, since it will no longer include any potential base layers in the contract.~~
Also, regarding the Windows specific blob format (where tar paths must be prefixed with `Files/`), see the last paragraph of [this spec page](https://github.com/buildpacks/spec#interpreting-paths-for-windows), as it is a blanket statement that covers all of the spec. Therefore we did not add the prefix to this dist spec specifically.
> Update Distribution Spec for Windows vs Linux Buildpackages

- buildpack.md
* Specifies interface of exec.d executables
* Specifies format of output
* Adds exec.d to launch process
Resolves #141 
One difference between the implementation here and the [RFC](https://github.com/buildpacks/rfcs/blob/main/text/0057-exec.d-shell-free-profile-d.md) is that the PR specifies the `exec.d` binaries are executed before `profile.d` scripts. This change was made to keep the implementation simple. It is easier to process exec.d output in the launch process before we `exec` Bash. Therefore I think this order is preferable if there is no functional reason to prefer the order in the RFC.
> Adds exec.d to buildpack API

- buildpack.md
Stack ID requirements have been removed from the buildpack specification. PR #154 moves these requirements to the platform specification with the other stack requirements.
* Resolves #140
> Any stack buildpacks

- platform.md
Add build.bom.buildpack to report.toml
The information included in the build BOM should have the same schema as the image BOM (io.buildpacks.build.metadata).
> Update build bom

- platform.md
Daemon cache images are not used due to performance reasons. This updates the
analyzer description to be more specific (other phases already have the specific
language).
> Clarify that cache image must be in a registry.

- platform.md
The current description is inaccurate as of platform api 0.4. 
> Clarify that launcher OR symlink is the entrypoint

- platform.md
Allowing `<layers>/order.toml` to resolve before a builder's `/cnb/order.toml` will let platforms control the buildpacks to be executed from inside the same pod. A platform may mount `<layers>` to a container that executes prior to `/cnb/detector` and can write an `order.toml` to be consumed by `/cnb/detector` without knowing anything about the builder to be used.
> Add <layers>/order.toml to path resolution

- platform.md
> [RFC 0072] Set Image Working Directory to value of CNB_APP_DIR

- buildpack.md
This modifies the spec to prohibit buildpacks from creating layers with name `build`, `launch` or `store`. This is to acoid confusions with special metadata files like build.toml etc. which may conflict with the layer metadata files.
In the future, we should create an RFC to decouple these directories/files entirely so that we don't encounter such issues in the future when we want to add additional special metadata files.
Fixes #200
> Explicitly ban the use of special layer names in the BP spec

- platform.md
When the exit code exceeds 255 it is expressed modulo 256 when surfaced in bash, which can be confusing.
This PR attempts to avoid "special" exit codes as described here: https://tldp.org/LDP/abs/html/exitcodes.html
Lifecycle issue: https://github.com/buildpacks/lifecycle/issues/502
> Condense lifecycle exit codes

- platform.md
> Assume web is the default for older buildpacks

- buildpack.md
> Buildpacks contribute default process type

- buildpack.md
Implements the [spec changes described in RFC-0070](https://github.com/buildpacks/rfcs/blob/main/text/0070-new-buildpack-toml-keys.md#spec-changes).
Fixes #181
> Added new buildpack.toml fields from RFC-0070

- buildpack.md
> Updates exec.d on Windows

- buildpack.md
- platform.md
This only addresses regular buildpacks and leaves stack buildpacks out until we have a better idea about how they will fit into the spec. 
Solves part of #149 
New issue for stackpacks work #211 
Signed-off-by: dwillist <dthornton@vmware.com>
> relax mixin contract for buildpacks

- platform.md
First take at [this rfc](https://github.com/buildpacks/rfcs/blob/main/text/0075-move-analyze-phase.md)
> Move analyzer before detector

- platform.md
Signed-off-by: Sambhav Kothari <skothari44@bloomberg.net>
> Recommend different build/runtime user ids

- buildpack.md
Fixes several issues with the examples:
- First example has cache = true, but also applies to cache = false
- Second example has build = true, but also applies to build = false
- Third example does not clearly specify how layers are used
> Fix layer examples

- platform.md
* Add back `-cache-image` to analyzer so that we can check read/write access
* Remove `-order` from analyzer as it is no longer needed
* Put `analyzed.toml` and `stack.toml` back to the old schema
* Remove `-analyzed` from detector as it is no longer needed
> Update platform 0.7 to reflect pause in mixin validation

- README.md
- buildpack.md
Updates buildpack API version to 0.7 in README and platform spec.
> Updates buildpack API version in spec and README

- buildpack.md
Currently the spec doesn't state what <major> and <minor> are expected to be.
I am proposing that we scope them to only contain numbers which seems to be what the lifecycle is already expecting:
https://github.com/buildpacks/lifecycle/blob/a7428a55c2a14d8a37e84285b95dc63192e3264e/api/version.go#L13-L16
Going beyond specifying they should be numbers, I also want to specify "unsigned 64 bit" integer which further bounds api versions to be greater than (or equal to) zero and less than (or equal to) 1,844,674,4073,709,551,615.
> Clarify buildpack API must be u64 numbers

- distribution.md
This PR initiates spec'ing the new distribution API version (version 3).  
We envision the new distribution API would consist the artifact format and the delivery mechanism for the buildpacks core components, which include:
- Buildpackage
- Lifecycle
- Build Image
- Run Image
There is also a plan of include "Builder" specification in the new distribution spec, which would in-turn just reference the above mentioned components.
The entire process would be broken down into separate PRs (each one would specify a single component!)
This PR provides the artifact format for the Buildpacks.
> Distribution Specs (v3) - Buildpacks Artifact Format

- distribution.md
This PR consists the artifact format and the delivery mechanism for Buildpacks' Lifecycle.
> Distribution Specs (v3) - Lifecycle Distribution Spec

- platform.md
This should be pointed to platform/0.8 but that branch doesn't exist yet...
> Platform support for sBOM

- buildpack.md
> Buildpack support for sBOM

- distribution.md
This PR consists the artifact format and the delivery mechanism for Buildpacks' Build Image.
Major changes/addition involve:
* Removing "Stack" related fields from the image manifest and instead using Image Config's `os`, `architecture` field.
> Distribution Spec (v3) - Build Image Artifact format

- buildpack.md
> Fixes link to SBOM section in buildpack spec

- buildpack.md
This technically should have gone into `buildpack/0.8`. Because we are putting sbom files in `/layers/sbom`, `sbom` is now a reserved buildpack ID.
> Add sbom as a reserved buildpack ID

- platform.md
Fixes #276 (went with Option 1)
> Updates platform spec to improve performance when restoring launch sboms from daemon

- platform.md
> Clarify what -skip-restore means

- buildpack.md
When we released the new SBOM, we created the following problem:
* Old platforms (that expect to find the BOM in a label) can't upgrade their buildpacks to the 0.7 api - or if they do, the BOM will just disappear. This means that in order to use newer buildpacks, platform operators who were using the old BOM must also upgrade their platform to 0.8+. This is a more difficult migration path than we would like.
This PR proposes that buildpacks should be able to output both the old and the new BOM formats. Then older platforms will still have a BOM in the label, while newer platforms will have both.
> Add deprecation path for buildpacks using the legacy BOM format.

- platform.md
Per discussion in 1/13 working group. If the platform api had originally been worded this way, we could've released a lifecycle patch to allow both bom behaviors in the same buildpack api without any spec changes.
cc @matthewmcnew @samj1912 @ekcasey
> Make the platform api more agnostic about the buildpack api WRT bom support

- distribution.md
This PR consists the artifact format and the delivery mechanism for Buildpacks' Builder Image.
For the most part, the builder references the buildpacks components i.e. buildpackage, build-image and the lifecycle. 
PS: Links to lifecycle and build-image are broken, I'll fix that once those PRs are merged!
> Distribution Specs (v3) - Builder Distribution Spec

- platform.md
This change proposes that legacy boms output by older buildpacks be ignored on the newest platform. 
The lifecycle implementation could output a warning if any boms are ignored.
> Remove legacy bom for platform/0.9

- buildpack.md
> Process specific working directory

- platform.md
Signed-off-by: Sambhav Kothari <skothari44@bloomberg.net>
This is a follow up to my comment at https://github.com/buildpacks/spec/pull/288#issuecomment-1063397023. Just removing the `<buildpack-id>` in the path so that it is easier for the lifecycle to output this format (the lifecycle already creates this output but puts it in a label instead of this file) and also better for end users as they get a combined BOM.
> Change legacy sbom location to a top level combined one

- platform.md
To continue the conversation [here](https://buildpacks.slack.com/archives/CCP60GJLS/p1644440749308319).
See related imgutil PR: https://github.com/buildpacks/imgutil/pull/137.
> Add mechanism for platform to provide image creation time

- buildpack.md
Per RFC 100: https://github.com/buildpacks/rfcs/blob/main/text/0100-buildpack-input-vars.md
Fixes #294.
Split out markdown table whitespace commit to make the diff more clear - the meat is in commit 3883a60d68fdc2faa443916b478489088939d48a.
> Deprecate positional args to `build` and `detect` and add env vars

- platform.md
Update language to prefer the term "OCI registry" over "docker registry"
Signed-off-by: Aidan Delaney <adelaney21@bloomberg.net>
> Replace docker registry with OCI registry

- CODEOWNERS
This came up in the Team Lead WG today. Similar to platform and buildpack specs, there are more than 1 team lead that should sign off on changes here. @jromero made the case that distribution is an extension of platforms.
> add platform team lead as a co-codeowner of distribution spec

- buildpack.md
- platform.md
Per [RFC 0093](https://github.com/buildpacks/rfcs/blob/main/text/0093-remove-shell-processes.md).
Closes #244
Signed-off-by: Mikey Boldt <mboldt@vmware.com>
> Remove shell-specific logic from Buildpack API

- buildpack.md
Resolves https://github.com/buildpacks/spec/issues/145
> Add terminology section to the buildpack spec

- platform.md
When `-skip-restore` is passed the creator should still restore store.toml.
There is currently a bug in the lifecycle implementation, because the entire restore phase is skipped, but the restore phase includes store.toml restoration as of platform 0.7.
When platform API is 0.10 or above, the lifecycle will invoke the restore phase but with -skip-layers so that SBOM and layer metadata files are not written to buildpack layer directories.
> Makes creator spec internally consistent

- platform.md
As described in https://github.com/buildpacks/rfcs/blob/main/text/0112-launcher-sbom.md
> [RFC 0112] Platform API changes for lifecycle/launcher SBOM

- platform.md
[Hide whitespace](https://github.com/buildpacks/spec/pull/329/files?diff=split&w=1) and the diff will be nicer
> Clarify: `<kaniko-dir>` is an input to the extender

- platform.md
This seems to have been an oversight in implementing overridable process args - the launcher has access to buildpack API in `<layers>/config/metadata.toml` but it is not printed in the label, hence platforms do not have all the required information to display processes correctly (or at least, to allow end users to distinguish between overridable and non-overridable args).
For newer platform API (0.10 and above) we need to know the buildpack API to know if the process args are overridable or not (when there is more than one element in the command, the process is definitely from a newer buildpack, but if there is only one element in the command, the args could be overridable or not overridable depending on the buildpack API).
Having this information will allow platforms such as pack to …
> Add buildpack API to io.buildpacks.build.metadata label

- extensions/project-descriptor.md
The `<...>` references must be wrapped with backticks, or they are not rendered at all, making the spec hard to follow.
Example of the current broken rendering:
> MUST be in form . or , where is equivalent to .0
Signed-off-by: Ed Morley <501702+edmorley@users.noreply.github.com>
> Fix schema version markdown rendering in project-descriptor.md

- buildpack.md
> Deprecate version 0.3 of the buildpack API

- buildpack.md
> Deprecate version 0.4 of the buildpack API

- buildpack.md
> Deprecate version 0.5 of the buildpack API

- buildpack.md
> Deprecate version 0.6 of the buildpack API

- platform.md
> Deprecate version 0.6 of the platform API

- platform.md
> Deprecate version 0.5 of the platform API

- platform.md
> Deprecate version 0.4 of the platform API

- platform.md
> Deprecate version 0.3 of the platform API 

- buildpack.md
- platform.md
RFC https://github.com/buildpacks/spec/pull/109 defines a directory
allowing operators to set environment variables for detect and build
phases.  Specify how the buildpack phases should implement the
behavior.
> Define CNB_BUILD_CONFIG_DIR buildpack behavior

- platform.md
clicking on the link today results in a 404, which can be resolved by editing the URL in the browser as it is edited in this PR.
> fixes link to image extension md file

- platform.md
We would like to propose some enhancement to the run image resolution.
A possible implementation: https://github.com/buildpacks/lifecycle/pull/1024
> Enhanced run image resolution

- platform.md
This is related to https://github.com/buildpacks/lifecycle/issues/1098
As for now the Spec is missing to specify the need to update the Stack metadata so it will reflect new information after image rebase process
> add lifecycle output to update stack after rebase

- image_extension.md
extension.toml as defined by spec omits [metadata] section. 
Discussion via slack suggested this was non-intentional. 
This PR adds the metadata block to the spec definiton of the extension.toml file
> Allow metadata for extension.toml

- buildpack.md
Rather than allow special values of `*` we should just make all fields optional and interpret them as wildcard matches when omitted.
> Buildpack spec: clarify target requirements and matching logic

- buildpack.md
- image_extension.md
See conversation here: https://github.com/buildpacks/spec/pull/335#discussion_r1276297988
> Buildpack spec: rename distribution to distro

- buildpack.md
For further context, see https://cloud-native.slack.com/archives/C033DV8D9FB/p1691077392008629
> Remove CNB_TARGET_ID from the Buildpack API

- platform.md
Base images may still express this identifier as a label, but it will not be used by the lifecycle nor provided to buildpacks.
> Remove `target.id` from the lifecycle

- platform.md
Spec changes as required by the RFC https://github.com/buildpacks/rfcs/pull/301
Splitted from https://github.com/buildpacks/spec/pull/382
Refers to changes introduced in #383
> Platform API changes for image extension build contexts

- image_extension.md
Spec changes as required by the RFC https://github.com/buildpacks/rfcs/pull/301
Splitted from #382
> Changes for image extension build contexts

- platform.md
Platform API changes to enable exporting app image and cache image in parallel
> Platform API changes to enable exporting app image and cache image in parallel

- platform.md
Restores the specification for `CNB_STACK_ID` to the definition that was used prior to the docs refactor in #335.
Fixes #396.
> Correct specification for deprecated `CNB_STACK_ID`

- buildpack.md
The correct name for the field is `distros.version` (singular), rather than `distros.versions`.
The former is what is used elsewhere in the spec, and in the lifecycle implementation.
The plural form looks like a leftover from the rename in: https://github.com/buildpacks/spec/commit/8652ec5e492998e0233c7778b7217d8433f16663
Fixes #401.
> Correct name of `distros.version` field in `buildpack.toml`

- platform.md
Restores the specification for `CNB_STACK_ID` to the definition that was used prior to the docs refactor in #335.
Fixes #396.
Backport of #397.
> [platform/0.12] Correct specification for deprecated `CNB_STACK_ID`

- buildpack.md
The correct name for the field is `distros.version` (singular), rather than `distros.versions`.
Fixes #401.
Backport of #402.
> [buildpack/0.11] Correct name of `distros.version` field in `buildpack.toml`

- buildpack.md
The correct name for the field is `distros.version` (singular), rather than `distros.versions`.
Fixes #401.
Backport of #402.
> [buildpack/0.10] Correct name of `distros.version` field in `buildpack.toml`

- buildpack.md
Make it clear that the file descriptor/handle is not passed as an argument. In context the file descriptor/handle is presented after we describe $0 (an argument to the executable), it is easy to infer that the file descriptor/handle is a subsequent argument.
> Improve precision of exec.d input description

- buildpack.md
https://github.com/buildpacks/lifecycle/pull/1346
https://github.com/buildpacks/lifecycle/pull/1346#issuecomment-2086928218
> Restore cached layer metadata for `launch: true` & `cache: true` from cache as a fallback

- platform.md
Reference:
https://github.com/buildpacks/lifecycle/pull/1364
https://github.com/buildpacks/lifecycle/pull/1364#discussion_r1659308384
> Add `-run` flag to the `restorer` binary

- README.md
- platform.md
Release notes
This release of the Cloud Native Buildpacks Specification defines Platform API 0.14.
Additions
* The `restorer` accepts a `-run` flag (https://github.com/buildpacks/spec/pull/408)
> Finalize Platform 0.14

- buildpack.md
The `image-extension.md` link is broken. This PR fixes that.
> fix typo to image extension link
